### ISSUE TITLE
AAVE Loader error

### ISSUE THREAD

**Issue by bettercalloption** [Logarithm-Labs/fractal-defi#3]
https://github.com/Logarithm-Labs/fractal-defi/blob/9929b629ec8b40b8d737b5b3f14398d7f45d2a00/fractal/loaders/aave.py#L38-L53

Backslash in string add newline, so url and date parsing not working.

Also rates should be positive according to aave entity logic

**Comment by likeblood** [comment]
https://github.com/Logarithm-Labs/fractal-defi/pull/6
